[serverInfo]
port = ":8000"
ip = "localhost"

[googleOAuth]
clientId = "563566199483-hcbham6nk7alfh4hm2pqsntrbqsom9an.apps.googleusercontent.com"
clientSecret ="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"
callBackUrl = "http://localhost:8000/auth/login/callback"


[Paseto]
pasetoKey = "12345678901234567890123456789012"
