[serverInfo]
port = ":8000"
ip = "localhost"

[googleOAuth]
clientId = "563566199483-kqqhil88ljimv4thrb7p4941lsh2qscs.apps.googleusercontent.com"
clientSecret ="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"
callBackUrl = "http://localhost:8000/login/callback"


[Paseto]
pasetoKey = "12345678901234567890123456789012"
